### ISSUE TITLE
Upload error messages aren't displaying

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/blender-media#5]
- [x] Display error messages
- [x] Display readable message for server errors

**Comment by freekmurze** [comment]
Which error message(s) are not displaying?

**Comment by sebastiandedeyne** [comment]
The upload error messages, renamed the issue for clarity.

**Comment by sebastiandedeyne** [comment]
Fixed

**Comment by sebastiandedeyne** [comment]
Still breaks on some specific error's (e.g. entity too large exception)

**Comment by sebastiandedeyne** [comment]
To be resolved with #8
